# Generated by Django 4.2 on 2023-04-11 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=300, verbose_name='Наименование компании')),
                ('specialization', models.TextField(max_length=1000, null=True, verbose_name='Специализация компании')),
                ('description', models.TextField(max_length=3000, null=True, verbose_name='Описание компании')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создание')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления')),
                ('is_deleted', models.BooleanField(default=False, null=True, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='Дата и время удаления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Профиль работадателя')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(verbose_name='Телефон номера')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('location', models.TextField(max_length=300, null=True, verbose_name='Местоположение соискателя')),
                ('sex', models.CharField(choices=[('Male', 'Мужской'), ('Female', 'Женский')], default='Male', max_length=100, null=True, verbose_name='Пол')),
                ('citizenship', models.TextField(max_length=300, null=True, verbose_name='Гражданство')),
                ('has_experience', models.BooleanField(default=False, null=True, verbose_name='Наличие опыта')),
                ('experience_year', models.FloatField(verbose_name='Годы опыта')),
                ('has_driving_lis', models.BooleanField(default=False, null=True, verbose_name='Наличие водительского права')),
                ('bio', models.TextField(max_length=3000, null=True, verbose_name='Биография пользователя')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='user_picture', verbose_name='Аватар')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создание')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления')),
                ('is_deleted', models.BooleanField(default=False, null=True, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='Дата и время удаления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_profile', to=settings.AUTH_USER_MODEL, verbose_name='Профиль заявителя')),
            ],
            options={
                'verbose_name': 'Профиль соискателя',
                'verbose_name_plural': 'Профили соискателей',
            },
        ),
    ]
