# Generated by Django 4.2 on 2023-04-12 22:54

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_account_is_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_applicant',
            field=models.BooleanField(null=True, verbose_name='Является соискателем'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11), accounts.models.validate_digits], verbose_name='Номер телефона'),
        ),
    ]
